# ========= Application Name ==========
spring.application.name=ems-backend

# ========= DataSource ==========
spring.datasource.url=jdbc:postgresql://localhost:5432/ems
spring.datasource.username=postgres
spring.datasource.password=super

# ========= JPA / Hibernate ==========
spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
#=======
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
# ========= Flyway ==========
spring.flyway.enabled=true
spring.flyway.baseline-on-migration=true
spring.flyway.locations=classpath:db/migration
spring.flyway.user=postgres
spring.flyway.password=super
spring.flyway.baseline-description=init
spring.flyway.baseline-version=0

#==========AOP/logging========

logging.level.com.practice.springboot.ems=INFO


#==========MongoDB configuration===========
spring.data.mongodb.uri=mongodb+srv://harsh:mongodbpassword@learningmongodb.7amtlmg.mongodb.net/ems_nosql?retryWrites=true&w=majority
# Connection URI:    mongodb+srv://harsh:mongodbpassword@learningmongodb.7amtlmg.mongodb.net/
# Database Name:     ems_nosql
# Connection Options: retryWrites=true&w=majority                  //ensures safe writes in Atlas.

#===========Spring Security===================

#spring.security.user.name = admin
#spring.security.user.password= admin@123