# ========= Application Name ==========
spring.application.name=ems-backend

# ========= DataSource ==========
spring.datasource.url=jdbc:postgresql://localhost:5432/ems
spring.datasource.username=postgres
spring.datasource.password=super

# ========= JPA / Hibernate ==========
spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ========= Flyway ==========
spring.flyway.enabled=true
spring.flyway.baseline-on-migration=true
spring.flyway.locations=classpath:db/migration
spring.flyway.user=postgres
spring.flyway.password=super
spring.flyway.baseline-description=init
spring.flyway.baseline-version=0
